### ISSUE TITLE
Super Node Reward is called / vsys / payment？

### ISSUE THREAD

**Issue by BigOceanGG** [virtualeconomy/v-systems#70]
Is it not different from ordinary transfer transaction?
How to distinguish the two kinds of transactions?

**Comment by ncying** [comment]
no, all payment transactions are the same in the main chain.

technically, the super-node team should handle this by their own tools. in v systems blockchain, super-node has more advanced rights to deal with their reward. however, the rights are monitored/regularized by all users in the community since they have the right to lease or cancel lease the coins to the super-node.

for more detail information, please contact the managing team of the project.

**Comment by BigOceanGG** [comment]
I mean, there's a lease transaction type, but the super node doesn't pay for the transaction type. For users, it just receives a transfer and is not sure whether it is lease reward or not

**Comment by faddat** [comment]
Correct.  

Lease rewards are not a special transaction type, and lease and unlease are user-initiated transactions directed towards a supernode, which supernodes do not pay for.

If there's nothing else, we will close this issue :).
