### ISSUE TITLE
Is it possible for the super node to embezzled all the proceeds？

### ISSUE THREAD

**Issue by ToWorld** [virtualeconomy/v-systems#92]
As the title said, 
    Is it possible for the super node to embezzled all the proceeds? If yes, how to resist such actions?

**Comment by ncying** [comment]
I can not understand the definition of "embezzled".

Base on the common sense of Blockchain technology, the only one(similar in the case of multi-signature) own the private key has the right to use the assets on chain. Why super-node or other user can embezzle it?

**Comment by ToWorld** [comment]
I mean that Is it possible for the super node to take the block reward for himself?

**Comment by ncying** [comment]
The general answer is NO. Since the reward is part of consensus, no one can beyond the consensus.

However, if you ask whether one can change the local state of its own balance? The answer is Yes. One can change their local state to whatever it like. But the common sense of the Blockchain technology is that base on **ALL** blocks information on chain, one can recover a **unique** global state. And this **unique** state handle the trust of the chain. This is part of every consensus. If you generated a block base on wrong global state, your block will be rejected by **ALL** other nodes, not only super-nodes.

**Comment by ToWorld** [comment]
Thanks a lot.
1.Can you give me a clue about the block reward distribution to people who leased out their coins to a particular super node from the code view?
2.Can you give me a clue about forking handle in the v systems from the code view?

**Comment by ncying** [comment]
1. Reward from system to super-node is included in consensus, however, if you means reward from super-node to individual user, I think it is no the part of consensus. As I mentioned in #88 SPoS is a consensus of **community autonomy**, super-node is decided by users. If super-node do `bad actions`, it is share by all community users. Then users will decided which one should be contend or not. If one super-node contend by others, it will loss more. Please check #88 and SPoS white paper for more detail information.

2. Please check the #88 for the detail of which fork node will pick.

**Comment by ToWorld** [comment]
Thanks a lot.
