### ISSUE TITLE
How to check the legality of a new block?

### ISSUE THREAD

**Issue by ToWorld** [virtualeconomy/v-systems#93]
```
             t0            t1            t2            t3
               --------------------------------------------------------> block time
A's view                   A            B            C
B's view      A            B            C
C's view                   A            B            C
               ---------------------------------------------------------> block time
```
At the time of t1, It is A's turn to mint from the view of A and C, however, It is B's turn to mint from the view of B which leads to a forking as follows:
```
                               preBlock
                          /                      \
                        /                         \
                       A's block          B's block
```
Therefore, each slot has its time to mint, 1)how to check the legality of a new block? 2)Does it depend on the local timestamp or blockTime?2)If A's block is not sent successfully and B's block is sent successfully, If B's block is received by A and C?

**Comment by ncying** [comment]
1. In SPoS consensus, a mint time is included in each block which represent the correct time that the minter need to generate the block. If the gap between block time and mint time is too large, the block will be rejected by other nodes. And the mint time is related with the slot of that super-node/minter and also the part of consensus.

2. If the fork appear, node will pick the correct fork by calculating the cumulating minting averaging balance(MAB) (not exact, but highly related). There is a clear explanation in #88. All new valid blocks received by nodes will put and broadcasted by P2P network.

3. In addition, in SPoS consensus, the right of super-node is related with its MAB. And MAB is highly related with staking. That's why SPoS consensus system is a community autonomy system.

**Comment by ToWorld** [comment]
Thanks a lot.
I basically understand what you mean but the following question:
Does block time mean the local unix time of a particular super node?

**Comment by ncying** [comment]
NTP time was used as base line.

**Comment by ToWorld** [comment]
I have one case as follows:
There are 10 super nodes with their own NTP time, and their NTP time is accurate.
Bad thing happened to one of super node which leaded to a problem to the super node, called node A.
Therefore, we assumed that the NTP time of node A was faster than normal node for about 3 seconds.
At the same time, it was time to mint in the view of node A and node A sent a new block to other super nodes, 1)Did other super nodes consider such new block valid? 2)If not, could you tell me about the rule of checking if a new block is valid?

**Comment by ncying** [comment]
1. It will check the gap between mint time and current NTP time, if it is too early/late, it will be rejected directly. (in particular, it can not generate a block from future, since the gap between two rounds is 1min, so 30s is used as presetting here )

2. It also checks the current NTP time with block time, if the block time is too late compared with the current NTP time, it will also be rejected by nodes. (15s is used here)

3. It will check the gap between mint time and last block's mint time if earlier than the previous block's mint time, it will be rejected directly too.

Therefore, the case above is a valid block. But, if the block generated earlier and within 4s, it may cause the fork. However, it is fork friendly systems. If fork happened, just solve the fork by the what decided in consensus. 

From the systems design view, this is not the perfect choice. But a simple and easy constraint is a good choice for the initial setting.

From the consensus design view, since all `harmful action` took by super-node will be shared by all community users, e.g. decreasing the reward rate, reduce the whole value of the chain, etc. Will rational users continue support such super-node on board? The gain from cooperation is far more than not. This is the basic setting in “Prisoner's Dilemma”, a basic concept in GAME THEORY. So, the best strategies for super-node is to follow the basic consensus and fix the issue ASAP to consolidate its mint right.

It may not exactly correct above, and wish this is helpful to you to understand the SPoS consensus and what we implemented in V Systems.

**Comment by ToWorld** [comment]
I basically understand the following questions:
1.How to check if a new block is valid?
2.How to handle a fork?
3.The economic theory behind v systems.

Thanks a lot.

**Comment by ToWorld** [comment]
I still have a confusion about the following concepts:
Minting time, Block time and NTP time.
Can you explain them to me?

**Comment by ncying** [comment]
Yes. That's the correct definition.

**Comment by ToWorld** [comment]
Does Current NTP time mean when the validation super node receives a new block and validates a new block?
If yes, which causes the following case:
If a new super node joins the validation nodes, it has to synchronize all blocks,  the gap between mint time and current NTP time of the validation node  is bigger than 1 minutes which causes a failed block.

**Comment by ncying** [comment]
1. The definition in the previous answer is to avoid the block from the future. The early/late is the same meaning with the different base concept(mint time or current NTP time). 
2. The mint time is also bounded by the previous block's mint time. That's the key for this validation check.
3. One can re-architecture the validation check. I think this is not the best and unique answer to this problem. But update the validation rule is also part of the consensus.
4. It is better to give a simpler and easier solution first. That's the current version of the implementation.
