### ISSUE TITLE
How many blocks we need to ensure a particular can't be rollback?

### ISSUE THREAD

**Issue by ToWorld** [virtualeconomy/v-systems#96]
If v systems has the rule to ensure a particular can't be rollback, such as after N blocks and so on.

**Comment by ncying** [comment]
In the current stage, the answer is "NO".

In the specific setting, one can set the max-rollback in the configuration. Since one can set a different value as max-rollback, then this is **not** part of the consensus. 

In addition, when a hard fork happened, one may use such tech to ensure the uniqueness of blockchain. This is just one of the choices, the final solution should be discussed with the users in the community.

**Comment by ToWorld** [comment]
Ok, thanks a lot.
